version: '3'
services:
 da1:
  image: antitree/private-tor
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  networks:
    tor_net:
      ipv4_address: 172.28.1.1
 da2:
  image: antitree/private-tor
  environment:
    ROLE: DA
  volumes:
    - ./tor:/tor
  networks:
    tor_net:
      ipv4_address: 172.28.1.2
 da3:
  image: antitree/private-tor
  environment:
    ROLE: DA
  volumes:
    - ./tor:/tor
  networks:
    tor_net:
      ipv4_address: 172.28.1.3
 relay_1:
  image: antitree/private-tor
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  networks:
    tor_net:
      ipv4_address: 172.28.2.1
 relay_2:
  image: antitree/private-tor
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  networks:
    tor_net:
      ipv4_address: 172.28.2.2
 relay_3:
  image: antitree/private-tor
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  networks:
    tor_net:
      ipv4_address: 172.28.2.3
 exit_1:
  image: antitree/private-tor
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  networks:
    tor_net:
        ipv4_address: 172.28.3.1
 exit_2:
  image: antitree/private-tor
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  networks:
    tor_net:
        ipv4_address: 172.28.3.2
 client:
  image: antitree/private-tor
  ports:
    # Setups a listener on host machine
    - "9050:9050"
    - "9051:9051"
  volumes:
    - ./tor:/tor
  environment:
    ROLE: CLIENT
  depends_on: 
    - da1
    - da2
    - da3
  networks:
    tor_net:
        ipv4_address: 172.28.4.1
 hs_1:
  image: antitree/private-tor
  environment:
    ROLE: HS
    # This will create a hidden service that points to
    # the service "hiddenservice" which is runing nginx. You can 
    # change this to whatever ip or hostname you want
    TOR_HS_PORT: "443"
    TOR_HS_ADDR: "hiddenservice"
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  links:
    - hiddenservice
  networks:
    tor_net:
        ipv4_address: 172.28.5.1
 hiddenservice:
  image: nginx
  volumes:
   - ./hiddenservice/nginx.conf:/etc/nginx/conf.d/default.conf
   - ./hiddenservice/cert.pem:/etc/nginx/cert.pem
   - ./hiddenservice/key.pem:/etc/nginx/key.pem
  environment:
   - NGINX_HOST=hiddenservice
   - NGINX_PORT=80
  ports:
   - "8443:80"
  networks:
    tor_net:
        ipv4_address: 172.28.5.2
networks:
    tor_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
